export const ActionTypes = {
  ADD_USERS: 'ADD_USERS',
  ADD_QUESTIONS: 'ADD_QUESTIONS',
  UPDATE_LOADER_STATUS: 'UPDATE_LOADER_STATUS',
  SET_CURRENT_QUESTION: 'SET_CURRENT_QUESTION',
  SET_IS_EDITING_QUESTION: 'SET_IS_EDITING_QUESTION',
  SET_USERNAME: 'SET_USERNAME',
  ADD_ANSWERS: 'ADD_ANSWERS',
  ADD_ANSWER: 'ADD_ANSWER',
  ADD_TEAM_FUND: 'ADD_TEAM_FUND',
  ADD_TEAM_FUND_TYPES: 'ADD_TEAM_FUND_TYPES',
  ADD_FUNDS_FOR_USER: 'ADD_FUNDS_FOR_USER',
  ADD_TASKS: 'ADD_TASK',
};
