export const ActionTypes = {
  ADD_USERS: 'ADD_USERS',
  ADD_QUESTIONS: 'ADD_QUESTIONS',
  UPDATE_LOADER_STATUS: 'UPDATE_LOADER_STATUS',
  CHANGE_RESULT_VIEW: 'CHANGE_RESULT_VIEW',
  SET_CURRENT_QUESTION: 'SET_CURRENT_QUESTION',
};
